### ISSUE TITLE
Where is the right place to discuss OWL*?

### ISSUE THREAD

**Issue by cmungall** [RDFstar/RDFstarTools#22]
I don't know if this tracker is the correct place for this.

I am interested in the question of semantics for RDF*. Of course, the existing OWL to RDF mapping can continue to be used, but this is suboptimal for various reasons

I proposed an outline for an OWL to RDF* mapping:

https://lists.w3.org/Archives/Public/public-owl-dev/2019AprJun/0003.html

And was meant with a resounding silence

**Comment by hartig** [comment]
This tracker indeed is not a good place for such a discussion because this repo is dedicated to the source code for extending Apache Jena with support for RDF*/SPARQL*.

I think that public-owl-dev should be a suitable place for this discussion. I am not on that list myself. I am not sure what is the reason for the silence. Maybe people are busy with other stuff? In my experience it may be useful to have the motivation and the idea fleshed out more, and having vendor support early on has also helped RDF*.

Now, it so happens that as of yesterday we have a new mailing list for discussing questions around RDF*/SPARQL*. See: https://lists.w3.org/Archives/Public/public-rdf-star/
However, I don't know how many people have already subscribed, and I am just about to go on vacation.

**Comment by cmungall** [comment]
Thanks! I will join and flesh out the ideas more
